{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exported_service",
    "query": {
     "query": "label_values(traefik_service_requests_total, exported_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$exported_service return code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_count{exported_service=~\"$exported_service\"}[$__range])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=~\"$exported_service\"}[$__interval]))/sum(increase(traefik_service_request_duration_seconds_count{exported_service=~\"$exported_service\"}[$__interval])) * 1000\n"
    }
   ]
  },
  {
   "title": "正常请求总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"$exported_service\",code=\"200\"}[$__interval])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "非200请求总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"$exported_service\",code!=\"200\"}[$__interval])) by (method, code)",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"$exported_service\"}[$__interval])) by (exported_service) / $__interval_ms * 1000",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "RT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(increase(traefik_service_request_duration_seconds_sum{exported_service=~\"$exported_service\"}[$__interval])) by (exported_service) \n  /\n  sum(increase(traefik_service_request_duration_seconds_count{exported_service=~\"$exported_service\"}[$__interval])) by (exported_service)\n) * 1000",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}